### ISSUE TITLE
In Windows Promtail does not respect `hosts` file

### ISSUE THREAD

**Issue by teyyubismayil** [grafana/loki#11292]
**Describe the bug**
In Windows Promtail does not respect `hosts` file because of the known [issue with netgo flag](https://github.com/golang/go/issues/57757). Suggested fix is building windows binaries without netgo flag

**To Reproduce**
1. Add some record for Loki server in `hosts` file
2. Start Promtail with specified host for Loki

**Expected behavior**
It is expected that Promtail will be able to connect to Loki, but host is not resolved

**Environment:**
 - OS: Windows

**Comment by cstyan** [comment]
It looks like the underlying problem has already been fixed, so newer go versions should solve this for us.

**Comment by sjansen1** [comment]
Any news on this issue? latest promtail still have this issue.

**Comment by JStickler** [comment]
Promtail is end of life (EOL) as of March 2, 2026. No future support or updates will be provided. All future feature development will occur in [Grafana Alloy](https://github.com/grafana/alloy).
