### ISSUE TITLE
Can't install Loki using the monolithic Helm chart from documentation 

### ISSUE THREAD

**Issue by Vaitek** [grafana/loki#12610]
**Describe the bug**
Monolithic Helm chart from documentation does not work.

**To Reproduce**

Hello! As described here: https://grafana.com/docs/loki/latest/setup/install/helm/install-monolithic/ i tried to install Loki using this values.yaml:

```yaml
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
singleBinary:
  replicas: 1
```

And it failed with error:

```bash
helm install --values values.yaml loki --namespace=loki grafana/loki
Error: INSTALLATION FAILED: execution error at (loki/templates/validate.yaml:31:4): You have more than zero replicas 
configured for both the single binary and simple scalable targets. If this was intentional change the deploymentMode 
to the transitional 'SingleBinary<->SimpleScalable' mode
```

After some searching, I modified the values.yaml to:

```yaml
deploymentMode: SingleBinary
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
singleBinary:
  replicas: 1
```

And i get next error:

```bash
helm install --values values.yaml loki --namespace=loki grafana/loki
Error: INSTALLATION FAILED: execution error at (loki/templates/validate.yaml:40:4): You must provide a schema_config for Loki, 
one is not provided as this will be individual for every Loki cluster. See https://grafana.com/docs/loki/latest/operations/storage/schema/ for schema information. For quick testing (with no persistence) 
add `--set loki.useTestSchema=true`
```

Finally, I modified the values.yaml to:

```yaml
deploymentMode: SingleBinary
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  schemaConfig:
    configs:
      - from: 2024-04-01
        object_store: filesystem
        store: tsdb
        schema: v13
        index:
          prefix: index_
          period: 24h
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
singleBinary:
  replicas: 1
```

And i was (maybe) successful:

```bash
helm install --values values.yaml loki --namespace=loki grafana/loki --create-namespace
NAME: loki
LAST DEPLOYED: Sun Apr 14 18:02:48 2024
NAMESPACE: loki
STATUS: deployed
REVISION: 1
NOTES:
***********************************************************************
 Welcome to Grafana Loki
 Chart version: 6.2.0
 Loki version: 3.0.0
***********************************************************************

Installed components:
* loki
```

**Expected behavior**
I was hoping the example from the documentation would be workable without having to search the source code.

**Environment:**
- `Ubuntu Server 22.04.3 virtual machine under Hyper-V on Windows 11`
- `Linux server 6.5.0-27-generic #28~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 15 10:51:06 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`
- `k3s version v1.29.1+k3s2 (57482a1c)`
- `Docker version 24.0.9, build 2936816`
- `helm version.BuildInfo{Version:"v3.13.1", GitCommit:"3547a4b5bf5edb5478ce352e18858d8a552a4110", GitTreeState:"clean", GoVersion:"go1.20.8"}`

WAIDW?

**Comment by javydekoning** [comment]
Same, this is broken as of `> 6.0.0` of the helm chart.

**Comment by JStickler** [comment]
I think this was fixed this morning in #12591.  Could you attempt the installation again and confirm if this fixes the problems you're having?

**Comment by javydekoning** [comment]
Confirmed, the fix works for me.

**Comment by evanrich** [comment]
I think this is still an issue.  getting 

```
 You have more than zero replicas configured for both the single binary and simple scalable targets. If this was intentional change the deploymentMode to the transitional 'SingleBinary<->SimpleScalable' 
```
from the following values:
```
deploymentMode: SingleBinary
loki:
  commonConfig:
    replication_factor: 3
  schemaConfig:
    configs:
    - from: "2024-01-01"
      store: tsdb
      index:
        prefix: loki_index_
        period: 24h
      object_store: filesystem
      schema: v13
  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    type: 's3'
    s3:
      endpoint: s3.server.tld
      region: us-west-1
      secretAccessKey: "${GRAFANA-LOKI-S3-SECRETACCESSKEY}"
      accessKeyId: "${GRAFANA-LOKI-S3-ACCESKEYID}"
      s3ForcePathStyle: false
      insecure: false
backend:
  extraArgs:
    - '-config.expand-env=true'
  extraEnv:
    - name: GRAFANA-LOKI-S3-ACCESKEYID 
      valueFrom:
        secretKeyRef:
          name: loki-secrets
          key: grafana-loki-s3-accessKeyId
    - name: GRAFANA-LOKI-S3-SECRETACCESSKEY
      valueFrom:
        secretKeyRef:
          name: loki-secrets
          key: grafana-loki-s3-secretAccessKey
singleBinary:
  replicas: 3
```

this is following the guide at https://grafana.com/docs/loki/latest/setup/install/helm/install-monolithic/
