### ISSUE TITLE
Promtail stops following logs after pod is restarted.

### ISSUE THREAD

**Issue by tomwilkie** [grafana/loki#127]
(Reported by a user, not confirmed yet)

**Comment by daixiang0** [comment]
run locally with docker is fine(grafana\promail\loki are all master tag)

**Comment by kovetskiy** [comment]
@tomwilkie that might be fixed by https://github.com/grafana/loki/pull/128

**Comment by dennybritz** [comment]
I am still seeing this. Given that the PR is merged and that I'm running the latest image with the `master` tag,  does this mean the PR did not fix it?

**Comment by tomwilkie** [comment]
@woodsaj says this is fixed?

**Comment by woodsaj** [comment]
yes, this was fixed by #281

**Comment by yubozhao** [comment]
@tomwilkie @woodsaj This issue still persist as of today.  The `positions.yaml` never add back the log path after the pod restarted/recreated.  I will try dig in to see what we can find

**Comment by yubozhao** [comment]
I haven't see https://github.com/grafana/loki/blob/b11583548746da29c005ae6d640681050355d5c4/pkg/promtail/targets/filetarget.go#L244 logged, when I watch promtail's log, during a pod's restarting/recreating time
