### ISSUE TITLE
Missing OCI-Releases

### ISSUE THREAD

**Issue by jgrnrt** [grafana/loki#15604]
**Describe the bug**
Loki oci releases cannot be used. 

**To Reproduce**
Look on the github-packages sites:
https://github.com/grafana/loki/pkgs/container/helm-charts%2Floki

https://github.com/orgs/grafana/packages?repo_name=helm-charts

Currently only the version "6.20.0-weekly.229" can be used with oci.

**Expected behavior**
Latest releases should be available in the correct repository ([helm-charts](https://github.com/grafana/helm-charts)). Also all the latest versions should be available. 

**Environment:**

**Screenshots, Promtail config, or terminal output**

**Comment by ChristianCiach** [comment]
Related to

* https://github.com/grafana/helm-charts/issues/3068

**Comment by onedr0p** [comment]
Fixed by https://github.com/grafana/loki/pull/16652 ?

**Comment by jgrnrt** [comment]
Current releases are not shown in the current [repository](https://github.com/grafana/loki/pkgs/container/helm-charts%2Floki). 


loki is still not shown in the correct [repository](https://github.com/orgs/grafana/packages?repo_name=helm-charts).

**Comment by onedr0p** [comment]
Sorry I meant it should be fixed by https://github.com/grafana/loki/pull/16652

**Comment by jgrnrt** [comment]
Yes, looks good.
