### ISSUE TITLE
Out of order inserts throw 500 errors

### ISSUE THREAD

**Issue by gouthamve** [grafana/loki#168]
Currently attempting to insert Out of Order throws 500 errors. We also don't support inserting two lines with the same timestamp.

**Comment by afiskon** [comment]
I'm afraid the support of out of order logs is mandatory for the release of Loki. Here is why.

I wrote a simple client library https://github.com/afiskon/promtail-client It's README includes a client example.

If you run it in a single process everything works just fine:
```
$ ./loki-example proto
2019/01/17 16:16:40 Error: The time is 2019-01-17 16:16:40.509173 +0300 MSK m=+0.019247359, i = 1
2019/01/17 16:16:41 Error: The time is 2019-01-17 16:16:41.512412 +0300 MSK m=+1.022477432, i = 2
2019/01/17 16:16:42 Error: The time is 2019-01-17 16:16:42.517708 +0300 MSK m=+2.027764858, i = 3
2019/01/17 16:16:43 Error: The time is 2019-01-17 16:16:43.519887 +0300 MSK m=+3.029934055, i = 4
```
However when I start multiple processes in different terminals logs get rejected with out-of-order errors:

```
2019/01/17 16:17:23 promtail.ClientProto: Unexpected HTTP status code: 500, message: rpc error: code = Unknown desc = Entry out of order
```

In other words currently Loki can be used only with a single process or mkicroservice. If your system has 2+ microservices, currently you just can't use Loki.

**Comment by olafure** [comment]
@woodsaj I notice this dates back since 19/12 and hasn't been labelled as a bug (as per the comment [above](https://github.com/grafana/loki/issues/168#issuecomment-455169837)).  Perhaps stick the label on so it gets some TLC :)

**Comment by woodsaj** [comment]
support for log entries with the same timestamp is being addressed in #288

**Comment by afiskon** [comment]
Hello,

I decided to test the patch using docker-compose and recent images from DockerHub. I still get:

```
2019/02/08 14:34:05 promtail.ClientProto: Unexpected HTTP status code: 400, message: Entry out of order
```

... in the second terminal window. Images versions:

```
$ docker-compose images
   Container         Repository       Tag       Image Id      Size
--------------------------------------------------------------------
temp_grafana_1    grafana/grafana    master   8905a7bc010e   232 MB
temp_loki_1       grafana/loki       master   66862f6b38aa   32.2 MB
temp_promtail_1   grafana/promtail   master   42300bf69b30   50.2 MB
```

Docker hub says that these images were updated ~20 minutes ago, thus I believe they should include recent changes. It seem that the patch didn't work. Or maybe I did something wrong?

**Comment by UzairM** [comment]
i am getting the same issue as afiskon

**Comment by afiskon** [comment]
Here are exact steps to reproduce:

1) Make sure no images are running:

```
$ docker-compose ps
Name   Command   State   Ports
------------------------------
```

2) Create a new empty directory:

```
mkdir loki-test
cd loki-test
```

3) Create docker-compose.yaml:

```
version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:master
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:master
    volumes:
      - /var/log:/var/log
    command:
      -config.file=/etc/promtail/docker-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    environment:
      GF_EXPLORE_ENABLED: "true"
    networks:
      - loki
```
4) Run `docker-compose pull`, then `docker-compose up`
5) Open http://localhost:3000/, login/password are admin/admin
6) Open http://localhost:3000/login, add a new Loki datasource with URL: `http://loki:3100` (`loki` is a local Docker network)
7) Build `loki-example` using the source code in README.md in this repository https://github.com/afiskon/promtail-client

```
$ pwd
/Users/eax/go/src/go-sandbox/loki-example
$ ls
main.go
$ go build
```

8) Execute `./loki-example proto` in one terminal window and simultaneously `./loki-example proto` in the second window.

Expected behavior: Both programs terminate normally. 

Actual behavior: There is a `Unexpected HTTP status code: 400, message: Entry out of order` error in the second terminal window.

**Comment by olafure** [comment]
Just to add, since the the prev comments didn't point out which images exactly, I can confirm bug still exists in grafana/loki:master-7527487 (which was built 2 hours ago).

**Comment by tomwilkie** [comment]
@olafure thanks for the info!  We don't support out of order, but we are supposed to support multiple entries with the same timestamp.  I'll build some unit tests to see whats going on here.

**Comment by AlekSi** [comment]
> We don't support out of order

Then you may want to rename issue before closing it. Otherwise, people will find it as fixed and closed, while in fact out of order entries will not be supported.

**Comment by UzairM** [comment]
I am having issues with multiple lines same time stamp.

**Comment by tomwilkie** [comment]
I built a bunch of unit tests (see #303) and a bunch more info logging (see #304) and we seem to be handling this correctly.  Please check you are using an up to date image version (`docker pull grafana/loki:master`) and try again, but pretty sure this works now - its working in our infra.

**Comment by afiskon** [comment]
I'm a little confused by latest comments. Can Loki currently add logs from more than one service? If not, are there any estimates when this might be implemented?

**Comment by woodsaj** [comment]
> Can Loki currently add logs from more than one service 

@afiskon you can send logs from multiple services, but the log streams from each service need to be unique (ie they have different labels).  The simplest way to ensure that is to just add a "source" label that describes where the logs are coming from.

**Comment by afiskon** [comment]
@woodsaj  Thank you a lot for the reply! I can confirm that Loki accepts logs with no problems from multiple services if they use different `source` value. I did corresponding changes to the README of my client library https://github.com/afiskon/promtail-client 

One more little question. We would like to use Loki in our project https://github.com/insolar/insolar However we would prefer to wait a little until the official release. Unfortunately I didn't manage to find a roadmap. Is there an estimate when approximately Loki will be released?

**Comment by hpoul** [comment]
@woodsaj any recommendation what I should do if i'd like to add client side logs (e.g. websites javascript console.log's or logs from a mobile app) to loki? it's impossible to use a user id or even device id as label.. but it's quite powerful to have user logs from the client side merged with logs from the server.. is this just out of scope for loki?

**Comment by woodsaj** [comment]
@hpoul sending logs from clients directly would be hard, especially as you have no control over the accuracy of the time on the client devices.   

The easiest solution would be to just have the logs from clients sent to a central logging service that then writes to Loki, setting the timestamp of each log message to the timestamp of when the log message was received by the logging service and not the timestamp provided by the client when when the log message was created.

**Comment by hpoul** [comment]
@woodsaj thanks for your fast response - well accuracy of the timestamp isn't really important, just that it's consistent within itself for each client.. since clients would send batches of log entries, this central logging service would set the same timestamp for possible hundreds of log lines.. would loki keep the "order" of log lines correct, if all have the same timestamp? also - could this be a feature of loki's ingester itself to tell it to rewrite timestamps? or when sending "ts": null - or a option on the stream when sending logs via the `/api/prom/push`? :) i really like the idea that i basically only need a single binary (plus a http proxy for auth and grafana) to capture logs..
