### ISSUE TITLE
`Please define loki.storage.bucketName.chunks` when using a monolithic minio helm deployment

### ISSUE THREAD

**Issue by RubenNL** [grafana/loki#18655]
**Describe the bug**
After PR https://github.com/grafana/loki/pull/13781 has been merged, I'm getting the `Please define loki.storage.bucketName.chunks` error.

I'm using the monolithic deployment documented here: https://grafana.com/docs/loki/latest/setup/install/helm/install-monolithic/, with 1 replica.

**To Reproduce**
1. Try to use the Helm values shown in the documentation shown here: https://grafana.com/docs/loki/latest/setup/install/helm/install-monolithic/
2. observe the error

**Expected behavior**
The documentation should provide a working deployment.  
I'm not sure if the documentation should be updated or the code itself.

The values.yaml seems to be working fine with chart 6.33.0.

**Environment:**
 - Infrastructure: k8s
 - Deployment tool: helm+flux

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

This is my exact values.yaml:

```
backend:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
chunksCache:
  enabled: false
compactor:
  replicas: 0
deploymentMode: SingleBinary
distributor:
  replicas: 0
indexGateway:
  replicas: 0
ingester:
  replicas: 0
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
  pattern_ingester:
    enabled: true
  ruler:
    enable_api: true
  schemaConfig:
    configs:
    - from: "2024-04-01"
      index:
        period: 24h
        prefix: loki_index_
      object_store: s3
      schema: v13
      store: tsdb
lokiCanary:
  enabled: false
minio:
  enabled: true
  resources:
    limits:
      memory: 1Gi
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
read:
  replicas: 0
resultsCache:
  enabled: false
singleBinary:
  replicas: 1
test:
  enabled: false
write:
  replicas: 0
```

Only changes here is a memory limit for `minio`, and I disabled authentication on loki, which shouldn't affect the error.

Here's a screenshot of the error (I can't select text from this box, so you'll have to do with this)

<img width="449" height="74" alt="Image" src="https://github.com/user-attachments/assets/b54760bc-c06c-4bb2-acc4-70792c771ce7" />

**Comment by mrbnd** [comment]
The same problem, it looks like this [PR](https://github.com/grafana/loki/pull/13781) does not take into account when build in minio used.

**Comment by tobiabocchi** [comment]
I also just noticed this problem using `simpleScalable` with local minio.
There also seems to be a typo in the error logged: `Please define loki.storage.bucketName.chunks` it should be `Please define loki.storage.bucketNames.chunks` instead (note the additional `s` after `bucketName`)

**Comment by jkroepke** [comment]
The problem should be fixed by https://github.com/grafana/loki/pull/18653

**Comment by mrbnd** [comment]
@jkroepke yes, but the problem still persists with latest available version
`Helm upgrade failed for release loki-p2p/loki with chart loki@6.34.0: execution error at (loki/templates/validate.yaml:46:4): Please define loki.storage.bucketName.chunks`

**Comment by jkroepke** [comment]
> but the problem still persists with latest available version

Sure, a fix should be included in the next weekly release.

**Comment by alex-berger** [comment]
This is still not correct for users of `structuredConfig` that explicitly override config, for example I have something like this:

```yaml
    loki:
      structuredConfig:
        common:
          storage:
            object_store:
              s3:
                bucket_name: "{{ .Values.aws.bucket }}"
                region: "{{ .Values.aws.region }}"
                endpoint: "s3.amazonaws.com"
                max_retries: 5
                bucket_lookup_type: "path"
```

And in that case setting `loki.storage.bucketName.chunks` is not necessary either.

**Comment by sebEg** [comment]
We get `Please define loki.storage.bucketName.ruler`, because we do not use s3 to store loki rules. It would be nice to also revert this check

**Comment by jkroepke** [comment]
@sebEg this PR should fix this.

@alex-berger this will be fixed in a follow-PR.

**Comment by sebEg** [comment]
@jkroepke You mean https://github.com/grafana/loki/pull/18653? I think we will still run into the error, because we use s3 to store the chunks, but mount rules via `ConfigMap`.

I would suggest to also revert this check: https://github.com/grafana/loki/pull/13781/files#diff-2b7d0f5125bd2b11d569d3e2af76208b35d1876085cc0875cfe88529283ed31cR49-R51

**Comment by jkroepke** [comment]
@sebEg I mean https://github.com/grafana/loki/pull/18665

**Comment by RubenNL** [comment]
Helm release 5.35.0 is out, which fixes the issue for me.

**Comment by jkroepke** [comment]
@sebEg could you create a distinct issue for your use-case place? It would be better to discuss this internally.

**Comment by Carl-NRCan** [comment]
We still have the "Please define loki.storage.bucketNames.ruler" on Helm 6.37.0

**Comment by Carl-NRCan** [comment]
We still have the "Please define loki.storage.bucketNames.ruler" on Helm 6.37.0 is it somewhat related ?

**Comment by wwyhy** [comment]
same issue with helm chart 6.37.0, we are using secret for the configuration(configObjectName: loki-config).

chart loki@6.37.0: execution error at (loki/templates/validate.yaml:46:4): Please define loki.storage.bucketNames.chunks

**Comment by jkroepke** [comment]
If you encounter "Please define loki.storage.bucketNames.chunks", please post your values.yaml

@JStickler could you please re-open this issue? Thank you.

**Comment by wwyhy** [comment]
@jkroepke 
here is the partial config of value.yaml, because we are using "configObjectName: loki-config", so we don't need the loki.storage.bucketNames.chunks definition. 

so hope to revert this check: https://github.com/grafana/loki/pull/13781/files#diff-2b7d0f5125bd2b11d569d3e2af76208b35d1876085cc0875cfe88529283ed31cR49-R51 


    loki:
      generatedConfigObjectName: ""
      configStorageType: Secret
      configObjectName: loki-config
      structuredConfig:
        schema_config:
          configs:
          - from: "2025-08-25"
            index:
              prefix: loki_index_
              period: 24h
            store: tsdb
            object_store: azure
            schema: v13

**Comment by jkroepke** [comment]
Thanks, I also didn’t have "configObjectName" in mind. I think I have a solution for this now.

**Comment by jkroepke** [comment]
If someone is able to test https://github.com/grafana/loki/pull/19051, it would be helped to prevent another failured release.

**Comment by Carl-NRCan** [comment]
Still an issue on 6.40.0

**Comment by flansen** [comment]
This issue happens to us with 6.45.1 using SingleBinary deployment after upgrading from 6.44.0

```yaml
deploymentMode: SingleBinary
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        index:
          prefix: loki_index_
          period: 24h
        object_store: filesystem
        schema: v13
  limitsConfig:
    maxChunksPerQuery: 1000000
    maxQuerySeries: 250000
    maxStreamsMatchersPerQuery: 500
  server:
    http_listen_port: 3100
    grpc_listen_port: 9095
  compactor:
    compaction_interval: 10m
    delete_request_store: filesystem
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
    retention_enabled: true
    working_directory: /tmp/loki/compactor
  ingester:
    lifecycler:
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1
```

**Comment by mts-dyt** [comment]
This still an issue with 6.45.x : 
- deploymentMode : SimpleScalable
- Storage: Azure Blob

**Comment by AKhozya** [comment]
Yep, pinned 6.44.0 - breaks after upgrading to 6.45.2

**Comment by jkroepke** [comment]
post your values.yaml - it wont help to just mention it doesnt work.

**Comment by jlaska** [comment]
> post your values.yaml - it wont help to just mention it doesnt work.

Same issue for me, I pinned to `6.44.0` and I'm using the following `values.yaml`

```yaml
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  schemaConfig:
    configs:
      - from: 2024-01-01
        store: tsdb
        index:
          prefix: loki_index_
          period: 24h
        object_store: filesystem
        schema: v13
  compactor:
    retention_enabled: true
    working_directory: /var/loki/compactor
    retention_delete_delay: 2h
    compaction_interval: 1h
    delete_request_store: filesystem
  limits_config:
    retention_period: 720h
  podSecurityContext:
    fsGroupChangePolicy: "OnRootMismatch"

deploymentMode: SingleBinary

singleBinary:
  persistence:
    storageClass: synology-nfs-csi
  replicas: 1
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
```

**Comment by jkroepke** [comment]
https://github.com/grafana/loki/pull/19675 should fix issues with filesystem storage.

**Comment by mrbnd** [comment]
@jkroepke 6.46.0 problem returned back when use local minio + `deploymentMode: Distributed`

`Helm upgrade failed for release loki/lokistorage with chart loki@6.46.0: execution error at (loki/templates/ruler/statefulset-ruler.yaml:25:12): Please define loki.storage.bucketNames.chunks`

```
  values:
    loki:
      auth_enabled: false
      containerSecurityContext:
        readOnlyRootFilesystem: false
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: index_
              period: 24h
      ingester:
        chunk_encoding: snappy
        max_chunk_age: 24h
      tracing:
        enabled: true
      bloom_build:
        enabled: true
        builder:
          planner_address: '{{ include "loki.bloomPlannerAddress" . }}'
        planner:
          planning_interval: 6h
          retention:
            enabled: true
      bloom_gateway:
        enabled: true
        client:
          addresses: '{{ include "loki.bloomGatewayAddresses" . }}'
      querier:
        # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
        max_concurrent: 32
      commonConfig:
        path_prefix: /var/loki
        replication_factor: 1
        compactor_address: '{{ include "loki.compactorAddress" . }}'
      server:
        http_listen_port: 3100
        grpc_listen_port: 9095
        http_server_read_timeout: 10m
        http_server_write_timeout: 10m
        http_server_idle_timeout: 10m
        grpc_server_max_recv_msg_size: 204857600
        grpc_server_max_send_msg_size: 204857600
      frontend:
        scheduler_address: '{{ include "loki.querySchedulerAddress" . }}'
        tail_proxy_url: '{{ include "loki.querierAddress" . }}'
        grpc_client_config:
            max_recv_msg_size: 204857600
            max_send_msg_size: 204857600
      frontend_worker:
        scheduler_address: '{{ include "loki.querySchedulerAddress" . }}'
        grpc_client_config:
            max_recv_msg_size: 204857600
            max_send_msg_size: 204857600
      compactor:
        retention_enabled: true
        delete_request_store: s3
        #working_directory: /var/loki/retention
        compaction_interval: 10m
        retention_delete_delay: 1h
      limits_config:
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        max_cache_freshness_per_query: 10m
        split_queries_by_interval: 30m
        query_timeout: 15m
        volume_enabled: true
        max_entries_limit_per_query: 900000000
        max_line_size: 0
        max_query_parallelism: 128
        max_global_streams_per_user: 0
        retention_period: 168h # 1 week
        bloom_creation_enabled: true
        bloom_split_series_keyspace_by: 1024
        bloom_gateway_enable_filtering: true
        max_query_series: 1000
        max_label_names_per_series: 30
      ruler:
        enable_api: true
        alertmanager_url: "http://alertmanager:9093"
        remote_write:
          enabled: true
          client:
            url: "http://prometheus:9090/api/v1/write"
    deploymentMode: Distributed

    queryScheduler:
      replicas: 2

    backend:
      replicas: 0

    read:
      replicas: 0

    write:
      replicas: 0

    lokiCanary:
      enabled: true
      extraArgs:
        - -user=$(LOKI_USERNAME)
        - -pass=$(LOKI_PASSWORD)
      extraEnv:
      - name: LOKI_USERNAME
        valueFrom:
          secretKeyRef:
            name: loki-credentials
            key: LOKI_USERNAME
      - name: LOKI_PASSWORD
        valueFrom:
          secretKeyRef:
            name: loki-credentials
            key: LOKI_PASSWORD
    test:
      enabled: false

    gateway:
      nodeSelector:
        workload: monitoring
      tolerations:
      - key: monitoring
        operator: Exists
        effect: "NoSchedule"
      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
          cert-manager.io/cluster-issuer: letsencrypt
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
          nginx.ingress.kubernetes.io/proxy-body-size: 50m
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: basic-auth-secret
          nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
        hosts:
        - host: some_host
          paths:
            - path: /
              pathType: Prefix
        tls:
        - secretName: some_ssl
          hosts:
            - some_host
      basicAuth:
        enabled: false # enabled above by auth-type annotation
        existingSecret: basic-auth-secret

    ingester:
      nodeSelector:
        workload: monitoring
      tolerations:
      - key: monitoring
        operator: Exists
        effect: "NoSchedule"
      replicas: 4

    distributor:
      nodeSelector:
        workload: monitoring
      tolerations:
      - key: monitoring
        operator: Exists
        effect: "NoSchedule"
      replicas: 3
      maxUnavailable: 2

    querier:
      nodeSelector:
        workload: monitoring
      tolerations:
      - key: monitoring
        operator: Exists
        effect: "NoSchedule"
      replicas: 6
      maxUnavailable: 2
      resources:
        requests:
          cpu: 700m
          memory: 4Gi
        limits:
          cpu: 1
          memory: 5Gi

    queryFrontend:
      nodeSelector:
        workload: monitoring
      tolerations:
      - key: monitoring
        operator: Exists
        effect: "NoSchedule"
      replicas: 2
      maxUnavailable: 1

    indexGateway:
      nodeSelector:
        workload: monitoring
      tolerations:
      - key: monitoring
        operator: Exists
        effect: "NoSchedule"
      replicas: 2
      maxUnavailable: 1

    compactor:
      nodeSelector:
        workload: monitoring
      tolerations:
      - key: monitoring
        operator: Exists
        effect: "NoSchedule"
      extraArgs:
        - -log.level=debug
      replicas: 1
      requests:
          cpu: 1
          memory: 1000Mi
      limits:
        cpu: 3
        memory: 2000Mi

    bloomGateway:
      nodeSelector:
        workload: monitoring
      tolerations:
      - key: monitoring
        operator: Exists
        effect: "NoSchedule"
      extraArgs:
      - -log.level=debug
      replicas: 1
      resources:
        requests:
          cpu: 200m
          memory: 300Mi
        limits:
          cpu: 400m
          memory: 500Mi

    bloomBuilder:
      nodeSelector:
        workload: monitoring
      tolerations:
      - key: monitoring
        operator: Exists
        effect: "NoSchedule"
      replicas: 2
      maxUnavailable: 1
      extraArgs:
      - -log.level=debug
      resources:
        requests:
          cpu: 400m
          memory: 700Mi
        limits:
          cpu: 500m
          memory: 800Mi
      extraVolumes:
        - name: blooms
          emptyDir: {}
      extraVolumeMounts:
        - name: blooms
          mountPath: /var/loki/blooms

    bloomPlanner:      
      nodeSelector:
        workload: monitoring
      tolerations:
      - key: monitoring
        operator: Exists
        effect: "NoSchedule"
      extraArgs:
      - -log.level=debug
      replicas: 1
      resources:
        requests:
          cpu: 300m
          memory: 500Mi
        limits:
          cpu: 500m
          memory: 700Mi

    patternIngester:
      nodeSelector:
        workload: monitoring
      tolerations:
      - key: monitoring
        operator: Exists
        effect: "NoSchedule"

    ruler:
      nodeSelector:
        workload: monitoring
      tolerations:
      - key: monitoring
        operator: Exists
        effect: "NoSchedule"

    overridesExporter:
      nodeSelector:
        workload: monitoring
      tolerations:
      - key: monitoring
        operator: Exists
        effect: "NoSchedule"

    chunksCache:
      nodeSelector:
        workload: monitoring
      tolerations:
      - key: monitoring
        operator: Exists
        effect: "NoSchedule"

    minio:
      nodeSelector:
        workload: monitoring
      tolerations:
      - key: monitoring
        operator: Exists
        effect: "NoSchedule"
      enabled: true
      mode: standalone
      drivesPerNode: 1
      persistence:
        storageClass: "hcloud-volumes-xfs"
        size: 500Gi
      resources:
        requests:
          cpu: 300m
          memory: 10Gi
      statefulSetUpdate:
        updateStrategy: Recreate
      metrics:
        serviceMonitor:
          enabled: true
          includeNode: true
          namespace: loki

    monitoring:
      rules:
        enabled: true
        alerting: true
        additionalGroups:
        - name: Custom_loki_alerts
          rules:
          - alert: Loki_ingester_write_to_disk_queue_length
            labels:
              severity: critical
            expr: |
              sum by(namespace) (loki_ingester_flush_queue_length) > 5
            for: 3m
            annotations:
              summary: "Loki ingester write logs to disk queue too long(> 5) for 3m"
              description: |
                This issue indicates that the Loki ingester is experiencing delays in
                writing logs to the disk. Possible bottlenecks:
                - Minio(or other storage) issues
                - disk performance
                - overwhelming volume
                - insufficient resources allocated to the Loki
      serviceMonitor:
        enabled: true
```

**Comment by wooyey** [comment]
> [@jkroepke](https://github.com/jkroepke) 6.46.0 problem returned back when use local minio + `deploymentMode: Distributed`
> 
> `Helm upgrade failed for release loki/lokistorage with chart loki@6.46.0: execution error at (loki/templates/ruler/statefulset-ruler.yaml:25:12): Please define loki.storage.bucketNames.chunks`

Have same issue.
It's look like last working version was `6.44.0`.

**Comment by jkroepke** [comment]
The fix for minio deployments is in https://github.com/grafana/loki/pull/19871

**Comment by mjnagel** [comment]
Just opened https://github.com/grafana/loki/issues/19872 as well for the ruler bucket issues. Not sure if that's an easy fix you could include @jkroepke ? Also happy to try and PR this one following your approach for the chunks if it's the same fix?

**Comment by gurpalw** [comment]
```
1: Error: execution error at (loki/templates/write/statefulset-write.yaml:50:28): Please define loki.storage.bucketNames.chunks Use --debug flag to render out invalid YAML
```

this is still happening for minio enabled deployments via simple scalable mode in 6.46.0

**Comment by jkroepke** [comment]
@gurpalw that might be expected. The fix https://github.com/grafana/loki/pull/19871 has been merged after 6.46 release and is not released yet.

**Comment by mrbnd** [comment]
@jkroepke new problem with new release(6.48.0).

k -n loki logs lokistorage-compactor-0

```
level=error ts=2025-12-10T05:33:11.816995038Z caller=log.go:223 msg="error running loki"
err="init compactor: failed to init delete store: failed to get s3 object: operation error S3: GetObject, resolve auth scheme:
resolve endpoint: endpoint rule error, 
Custom endpoint `lokistorage-minio.loki.svc:9000` was not a valid URI\nerror initialising module:
compactor\ngithub.com/grafana/dskit/modules
(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:138\ngithub.com/grafana/dskit/module
.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/loki/v3/pkg/loki
(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:549\nmain.main\n\t/src/loki/cmd/loki/main.go:130\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:283\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700"
```


Manual fix helps
`k -n loki edit cm loki`

```
      storage:
        s3:
          access_key_id: root-user
          bucketnames: chunks
          endpoint: lokistorage-minio.loki.svc:9000 <- Add http:// ->  http://lokistorage-minio.loki.svc:9000 solve problem
          insecure: true
          s3forcepathstyle: true
          secret_access_key: supersecretpassword
```

**Comment by jkroepke** [comment]
@mrbnd The issue you mention is not related to the helm chart. See https://github.com/grafana/loki/issues/19908
