### ISSUE TITLE
Growing heap size and goroutines after queries - memory leak?

### ISSUE THREAD

**Issue by jfolz** [grafana/loki#4119]
**Describe the bug**
Heap size and number of goroutines of the Loki process grows permanently after queries. This is most obvious with a Grafana dashboard that runs multiple Loki queries and refreshes regularly.

**To Reproduce**
1. Run non-cluster Loki 2.3.0.
2. Run Promtail with the example `varlogs` scrape config.
3. Add Loki datasource to Grafana.
4. Enter query `{job=~"varlogs"} |~ "(?i)error"` into Grafana Explore UI with Loki datasource.
5. Set time to last 24 hours, line limit 5000 lines, and refresh 30 seconds.

**Expected behavior**
Heap size and number of goroutines of the Loki process is (relatively) stable.

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: binary from Github release page
 - Loki config: [loki.yml](https://github.com/grafana/loki/files/6950561/loki.yml.txt) (AFAIK the only "unusual" bits are zstd compression and very long 24h max chunk age/idle period)
 - Log volume last 48 hours:
   - 5-20 lines/second
   - 105M uncompressed
   - 1689 chunks
   - ~500 active streams

**Screenshots, Promtail config, or terminal output**
Metrics for the Loki process after running some tests:

![image](https://user-images.githubusercontent.com/3245870/128632162-a399e158-03c8-41fd-a384-20d3e6fa1efd.png)
Left: `go_memstats_sys_bytes` (green) and `go_memstats_heap_inuse_bytes` (yellow)
Right: `go_goroutines`

Heap increases by dozens of MB for every query and goroutines increase by 100+.

**Comment by cyriltovena** [comment]
Thanks for reporting,

Could you take a goroutine pprof profile at /debug/pprof/goroutines please ? Not seeing this on my side, could be because we use a different setup.

**Comment by jfolz** [comment]
<details>
<summary>OK that seems pretty obvious</summary>
<p>

```
goroutine profile: total 73811
70752 @ 0x43b225 0x4068cf 0x40654b 0x1baf849 0x472621
#       0x1baf848       github.com/klauspost/compress/zstd.(*blockDec).startDecoder+0x148       /src/loki/vendor/github.com/klauspost/compress/zstd/blockdec.go:215

2948 @ 0x43b225 0x4068cf 0x40654b 0x1bba593 0x472621
#       0x1bba592       github.com/klauspost/compress/zstd.(*Decoder).startStreamDecoder+0x2b2  /src/loki/vendor/github.com/klauspost/compress/zstd/decoder.go:491

16 @ 0x43b225 0x4068cf 0x40654b 0x1478b79 0x472621
#       0x1478b78       github.com/cortexproject/cortex/pkg/chunk.(*Fetcher).worker+0x218       /src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/chunk_store_utils.go:128

16 @ 0x43b225 0x46e698 0x46e66e 0x489499 0xc2c876 0x1e05a79 0x472621
#       0x46e66d        sync.runtime_notifyListWait+0xcd                                        /usr/local/go/src/runtime/sema.go:513
#       0x489498        sync.(*Cond).Wait+0x98                                                  /usr/local/go/src/sync/cond.go:56
#       0xc2c875        github.com/cortexproject/cortex/pkg/util.(*PriorityQueue).Dequeue+0x75  /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/priority_queue.go:115
#       0x1e05a78       github.com/grafana/loki/pkg/ingester.(*Ingester).flushLoop+0x98         /src/loki/pkg/ingester/flush.go:210

12 @ 0x43b225 0x4068cf 0x40654b 0xc14546 0x472621
#       0xc14545        github.com/cortexproject/cortex/pkg/util/services.(*BasicService).AddListener.func1+0x65        /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:344

10 @ 0x43b225 0x44c397 0xc10ad8 0xc10a11 0xc2a8a8 0xc10682 0x472621
#       0xc10ad7        github.com/cortexproject/cortex/pkg/util/services.(*BasicService).awaitState+0x97       /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:294
#       0xc10a10        github.com/cortexproject/cortex/pkg/util/services.(*BasicService).AwaitTerminated+0x50  /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:290
#       0xc2a8a7        github.com/cortexproject/cortex/pkg/util.(*moduleService).run+0x47                      /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/module_service.go:71
#       0xc10681        github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main+0x401            /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:190

3 @ 0x43b225 0x44c397 0xc14b05 0xc10682 0x472621
#       0xc14b04        github.com/cortexproject/cortex/pkg/util/services.NewTimerService.func1+0x104   /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/services.go:31
#       0xc10681        github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main+0x401    /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:190

2 @ 0x43b225 0x4068cf 0x40650b 0x985f05 0x472621
#       0x985f04        google.golang.org/grpc.(*addrConn).resetTransport+0x464 /src/loki/vendor/google.golang.org/grpc/clientconn.go:1214

2 @ 0x43b225 0x4068cf 0x40650b 0xc149c8 0xc10682 0x472621
#       0xc149c7        github.com/cortexproject/cortex/pkg/util/services.NewIdleService.func1+0x47     /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/services.go:13
#       0xc10681        github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main+0x401    /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:190

2 @ 0x43b225 0x4068cf 0x40654b 0xc14966 0x472621
#       0xc14965        github.com/cortexproject/cortex/pkg/util/services.(*Manager).AddListener.func1+0x65     /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/manager.go:244

2 @ 0x43b225 0x43347b 0x46c875 0x4e7fa5 0x4e9095 0x4e9077 0x53652f 0x54b1f1 0x5b7482 0x4bc267 0x8ccd29 0x8cccc2 0x8cd765 0x908465 0x472621
#       0x46c874        internal/poll.runtime_pollWait+0x54                                     /usr/local/go/src/runtime/netpoll.go:222
#       0x4e7fa4        internal/poll.(*pollDesc).wait+0x44                                     /usr/local/go/src/internal/poll/fd_poll_runtime.go:87
#       0x4e9094        internal/poll.(*pollDesc).waitRead+0x1d4                                /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
#       0x4e9076        internal/poll.(*FD).Read+0x1b6                                          /usr/local/go/src/internal/poll/fd_unix.go:166
#       0x53652e        net.(*netFD).Read+0x4e                                                  /usr/local/go/src/net/fd_posix.go:55
#       0x54b1f0        net.(*conn).Read+0x90                                                   /usr/local/go/src/net/net.go:183
#       0x5b7481        bufio.(*Reader).Read+0x221                                              /usr/local/go/src/bufio/bufio.go:227
#       0x4bc266        io.ReadAtLeast+0x86                                                     /usr/local/go/src/io/io.go:328
#       0x8ccd28        io.ReadFull+0x88                                                        /usr/local/go/src/io/io.go:347
#       0x8cccc1        golang.org/x/net/http2.readFrameHeader+0x21                             /src/loki/vendor/golang.org/x/net/http2/frame.go:237
#       0x8cd764        golang.org/x/net/http2.(*Framer).ReadFrame+0xa4                         /src/loki/vendor/golang.org/x/net/http2/frame.go:492
#       0x908464        google.golang.org/grpc/internal/transport.(*http2Client).reader+0x1a4   /src/loki/vendor/google.golang.org/grpc/internal/transport/http2_client.go:1347

2 @ 0x43b225 0x43347b 0x46c875 0x4e7fa5 0x4e9095 0x4e9077 0x53652f 0x54b1f1 0x5b7482 0x4bc267 0x8ccd29 0x8cccc2 0x8cd765 0x90d5bb 0x992503 0x9a6b1f 0x472621
#       0x46c874        internal/poll.runtime_pollWait+0x54                                             /usr/local/go/src/runtime/netpoll.go:222
#       0x4e7fa4        internal/poll.(*pollDesc).wait+0x44                                             /usr/local/go/src/internal/poll/fd_poll_runtime.go:87
#       0x4e9094        internal/poll.(*pollDesc).waitRead+0x1d4                                        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
#       0x4e9076        internal/poll.(*FD).Read+0x1b6                                                  /usr/local/go/src/internal/poll/fd_unix.go:166
#       0x53652e        net.(*netFD).Read+0x4e                                                          /usr/local/go/src/net/fd_posix.go:55
#       0x54b1f0        net.(*conn).Read+0x90                                                           /usr/local/go/src/net/net.go:183
#       0x5b7481        bufio.(*Reader).Read+0x221                                                      /usr/local/go/src/bufio/bufio.go:227
#       0x4bc266        io.ReadAtLeast+0x86                                                             /usr/local/go/src/io/io.go:328
#       0x8ccd28        io.ReadFull+0x88                                                                /usr/local/go/src/io/io.go:347
#       0x8cccc1        golang.org/x/net/http2.readFrameHeader+0x21                                     /src/loki/vendor/golang.org/x/net/http2/frame.go:237
#       0x8cd764        golang.org/x/net/http2.(*Framer).ReadFrame+0xa4                                 /src/loki/vendor/golang.org/x/net/http2/frame.go:492
#       0x90d5ba        google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams+0x9a     /src/loki/vendor/google.golang.org/grpc/internal/transport/http2_server.go:473
#       0x992502        google.golang.org/grpc.(*Server).serveStreams+0x102                             /src/loki/vendor/google.golang.org/grpc/server.go:918
#       0x9a6b1e        google.golang.org/grpc.(*Server).handleRawConn.func1+0x3e                       /src/loki/vendor/google.golang.org/grpc/server.go:868

2 @ 0x43b225 0x43347b 0x46c875 0x4e7fa5 0x4e9095 0x4e9077 0x53652f 0x54b1f1 0x826279 0x5b6de8 0x5b6f6f 0x82c6e7 0x472621
#       0x46c874        internal/poll.runtime_pollWait+0x54             /usr/local/go/src/runtime/netpoll.go:222
#       0x4e7fa4        internal/poll.(*pollDesc).wait+0x44             /usr/local/go/src/internal/poll/fd_poll_runtime.go:87
#       0x4e9094        internal/poll.(*pollDesc).waitRead+0x1d4        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
#       0x4e9076        internal/poll.(*FD).Read+0x1b6                  /usr/local/go/src/internal/poll/fd_unix.go:166
#       0x53652e        net.(*netFD).Read+0x4e                          /usr/local/go/src/net/fd_posix.go:55
#       0x54b1f0        net.(*conn).Read+0x90                           /usr/local/go/src/net/net.go:183
#       0x826278        net/http.(*connReader).Read+0x1b8               /usr/local/go/src/net/http/server.go:800
#       0x5b6de7        bufio.(*Reader).fill+0x107                      /usr/local/go/src/bufio/bufio.go:101
#       0x5b6f6e        bufio.(*Reader).Peek+0x4e                       /usr/local/go/src/bufio/bufio.go:139
#       0x82c6e6        net/http.(*conn).serve+0xa46                    /usr/local/go/src/net/http/server.go:1977

2 @ 0x43b225 0x44c397 0x10e699c 0x472621
#       0x10e699b       github.com/prometheus/prometheus/tsdb/wal.(*WAL).run+0xbb       /src/loki/vendor/github.com/prometheus/prometheus/tsdb/wal/wal.go:332

2 @ 0x43b225 0x44c397 0x8f6c7f 0x8f75dd 0x91b6db 0x472621
#       0x8f6c7e        google.golang.org/grpc/internal/transport.(*controlBuffer).get+0xfe     /src/loki/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:407
#       0x8f75dc        google.golang.org/grpc/internal/transport.(*loopyWriter).run+0x1dc      /src/loki/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:527
#       0x91b6da        google.golang.org/grpc/internal/transport.newHTTP2Client.func3+0x7a     /src/loki/vendor/google.golang.org/grpc/internal/transport/http2_client.go:396

2 @ 0x43b225 0x44c397 0x8f6c7f 0x8f75dd 0x91cb77 0x472621
#       0x8f6c7e        google.golang.org/grpc/internal/transport.(*controlBuffer).get+0xfe     /src/loki/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:407
#       0x8f75dc        google.golang.org/grpc/internal/transport.(*loopyWriter).run+0x1dc      /src/loki/vendor/google.golang.org/grpc/internal/transport/controlbuf.go:527
#       0x91cb76        google.golang.org/grpc/internal/transport.newHTTP2Server.func2+0xd6     /src/loki/vendor/google.golang.org/grpc/internal/transport/http2_server.go:292

2 @ 0x43b225 0x44c397 0x9091da 0x472621
#       0x9091d9        google.golang.org/grpc/internal/transport.(*http2Client).keepalive+0x179        /src/loki/vendor/google.golang.org/grpc/internal/transport/http2_client.go:1421

2 @ 0x43b225 0x44c397 0x911b85 0x472621
#       0x911b84        google.golang.org/grpc/internal/transport.(*http2Server).keepalive+0x264        /src/loki/vendor/google.golang.org/grpc/internal/transport/http2_server.go:993

2 @ 0x43b225 0x44c397 0x97d9ec 0x472621
#       0x97d9eb        google.golang.org/grpc.(*ccBalancerWrapper).watcher+0xab        /src/loki/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:69

1 @ 0x40c6f4 0x46ec05 0xbc6565 0x472621
#       0x46ec04        os/signal.signal_recv+0xa4      /usr/local/go/src/runtime/sigqueue.go:168
#       0xbc6564        os/signal.loop+0x24             /usr/local/go/src/os/signal/signal_unix.go:23

1 @ 0x43b225 0x4068cf 0x40650b 0x1f1df54 0xbcae9a 0x472621
#       0x1f1df53       github.com/cortexproject/cortex/pkg/cortex.ignoreSignalHandler.Loop+0x33        /src/loki/vendor/github.com/cortexproject/cortex/pkg/cortex/server_service.go:65
#       0xbcae99        github.com/weaveworks/common/server.(*Server).Run.func1+0x39                    /src/loki/vendor/github.com/weaveworks/common/server/server.go:384

1 @ 0x43b225 0x4068cf 0x40650b 0xbcad3b 0x1f1e0f7 0x472621
#       0xbcad3a        github.com/weaveworks/common/server.(*Server).Run+0x15a                         /src/loki/vendor/github.com/weaveworks/common/server/server.go:424
#       0x1f1e0f6       github.com/cortexproject/cortex/pkg/cortex.NewServerService.func1.1+0x56        /src/loki/vendor/github.com/cortexproject/cortex/pkg/cortex/server_service.go:25

1 @ 0x43b225 0x4068cf 0x40654b 0x1ec0675 0x472621
#       0x1ec0674       github.com/cortexproject/cortex/pkg/alertmanager.init.0.func1+0x54      /src/loki/vendor/github.com/cortexproject/cortex/pkg/alertmanager/alertmanager.go:127

1 @ 0x43b225 0x4068cf 0x40654b 0xd36826 0x472621
#       0xd36825        github.com/cortexproject/cortex/pkg/ring/kv/consul.(*mockKV).loop+0x65  /src/loki/vendor/github.com/cortexproject/cortex/pkg/ring/kv/consul/mock.go:54

1 @ 0x43b225 0x43347b 0x46c875 0x4e7fa5 0x4e9095 0x4e9077 0x53652f 0x54b1f1 0x825cf8 0x472621
#       0x46c874        internal/poll.runtime_pollWait+0x54             /usr/local/go/src/runtime/netpoll.go:222
#       0x4e7fa4        internal/poll.(*pollDesc).wait+0x44             /usr/local/go/src/internal/poll/fd_poll_runtime.go:87
#       0x4e9094        internal/poll.(*pollDesc).waitRead+0x1d4        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
#       0x4e9076        internal/poll.(*FD).Read+0x1b6                  /usr/local/go/src/internal/poll/fd_unix.go:166
#       0x53652e        net.(*netFD).Read+0x4e                          /usr/local/go/src/net/fd_posix.go:55
#       0x54b1f0        net.(*conn).Read+0x90                           /usr/local/go/src/net/net.go:183
#       0x825cf7        net/http.(*connReader).backgroundRead+0x57      /usr/local/go/src/net/http/server.go:692

1 @ 0x43b225 0x43347b 0x46c875 0x4e7fa5 0x4eae12 0x4eadf4 0x537b65 0x555c72 0x554645 0xbbb2d7 0x831425 0xbcb006 0x472621
#       0x46c874        internal/poll.runtime_pollWait+0x54                                     /usr/local/go/src/runtime/netpoll.go:222
#       0x4e7fa4        internal/poll.(*pollDesc).wait+0x44                                     /usr/local/go/src/internal/poll/fd_poll_runtime.go:87
#       0x4eae11        internal/poll.(*pollDesc).waitRead+0x211                                /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
#       0x4eadf3        internal/poll.(*FD).Accept+0x1f3                                        /usr/local/go/src/internal/poll/fd_unix.go:401
#       0x537b64        net.(*netFD).accept+0x44                                                /usr/local/go/src/net/fd_unix.go:172
#       0x555c71        net.(*TCPListener).accept+0x31                                          /usr/local/go/src/net/tcpsock_posix.go:139
#       0x554644        net.(*TCPListener).Accept+0x64                                          /usr/local/go/src/net/tcpsock.go:261
#       0xbbb2d6        github.com/weaveworks/common/middleware.(*countingListener).Accept+0x36 /src/loki/vendor/github.com/weaveworks/common/middleware/counting_listener.go:22
#       0x831424        net/http.(*Server).Serve+0x284                                          /usr/local/go/src/net/http/server.go:2981
#       0xbcb005        github.com/weaveworks/common/server.(*Server).Run.func2+0x125           /src/loki/vendor/github.com/weaveworks/common/server/server.go:394

1 @ 0x43b225 0x43347b 0x46c875 0x4e7fa5 0x4eae12 0x4eadf4 0x537b65 0x555c72 0x554645 0xbbb2d7 0x9910bf 0xbcb06e 0x472621
#       0x46c874        internal/poll.runtime_pollWait+0x54                                     /usr/local/go/src/runtime/netpoll.go:222
#       0x4e7fa4        internal/poll.(*pollDesc).wait+0x44                                     /usr/local/go/src/internal/poll/fd_poll_runtime.go:87
#       0x4eae11        internal/poll.(*pollDesc).waitRead+0x211                                /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
#       0x4eadf3        internal/poll.(*FD).Accept+0x1f3                                        /usr/local/go/src/internal/poll/fd_unix.go:401
#       0x537b64        net.(*netFD).accept+0x44                                                /usr/local/go/src/net/fd_unix.go:172
#       0x555c71        net.(*TCPListener).accept+0x31                                          /usr/local/go/src/net/tcpsock_posix.go:139
#       0x554644        net.(*TCPListener).Accept+0x64                                          /usr/local/go/src/net/tcpsock.go:261
#       0xbbb2d6        github.com/weaveworks/common/middleware.(*countingListener).Accept+0x36 /src/loki/vendor/github.com/weaveworks/common/middleware/counting_listener.go:22
#       0x9910be        google.golang.org/grpc.(*Server).Serve+0x27e                            /src/loki/vendor/google.golang.org/grpc/server.go:786
#       0xbcb06d        github.com/weaveworks/common/server.(*Server).Run.func3+0x4d            /src/loki/vendor/github.com/weaveworks/common/server/server.go:413

1 @ 0x43b225 0x44c397 0x10265dc 0xc10682 0x472621
#       0x10265db       github.com/cortexproject/cortex/pkg/ring.(*Lifecycler).loop+0x1fb               /src/loki/vendor/github.com/cortexproject/cortex/pkg/ring/lifecycler.go:400
#       0xc10681        github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main+0x401    /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:190

1 @ 0x43b225 0x44c397 0x124cd2d 0x472621
#       0x124cd2c       go.opencensus.io/stats/view.(*worker).start+0xcc        /src/loki/vendor/go.opencensus.io/stats/view/worker.go:276

1 @ 0x43b225 0x44c397 0x149e712 0xc10682 0x472621
#       0x149e711       github.com/cortexproject/cortex/pkg/chunk.(*TableManager).loop+0x2d1            /src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/table_manager.go:229
#       0xc10681        github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main+0x401    /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:190

1 @ 0x43b225 0x44c397 0x14e6b91 0x472621
#       0x14e6b90       github.com/cortexproject/cortex/pkg/chunk/local.(*BoltIndexClient).loop+0x110   /src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/local/boltdb_index_client.go:81

1 @ 0x43b225 0x44c397 0x1c5afe7 0x472621
#       0x1c5afe6       github.com/grafana/loki/pkg/storage/stores/shipper/downloads.(*TableManager).loop+0x1c6 /src/loki/pkg/storage/stores/shipper/downloads/table_manager.go:98

1 @ 0x43b225 0x44c397 0x1c6523f 0x472621
#       0x1c6523e       github.com/grafana/loki/pkg/storage/stores/shipper/uploads.(*TableManager).loop+0x19e   /src/loki/pkg/storage/stores/shipper/uploads/table_manager.go:77

1 @ 0x43b225 0x44c397 0x1ca2e55 0x472621
#       0x1ca2e54       github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).loop.func2+0x134      /src/loki/pkg/storage/stores/shipper/compactor/compactor.go:173

1 @ 0x43b225 0x44c397 0x1dc1b73 0xc10682 0x472621
#       0x1dc1b72       github.com/cortexproject/cortex/pkg/ruler.(*Ruler).run+0x2f2                    /src/loki/vendor/github.com/cortexproject/cortex/pkg/ruler/ruler.go:455
#       0xc10681        github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main+0x401    /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:190

1 @ 0x43b225 0x44c397 0x1deb18c 0xc10682 0x472621
#       0x1deb18b       github.com/grafana/loki/pkg/distributor.(*Distributor).running+0xab             /src/loki/pkg/distributor/distributor.go:164
#       0xc10681        github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main+0x401    /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:190

1 @ 0x43b225 0x44c397 0x1df9872 0x1df9d0a 0x1e1f9db 0x472621
#       0x1df9871       github.com/grafana/loki/pkg/ingester.(*Checkpointer).PerformCheckpoint+0x331    /src/loki/pkg/ingester/checkpoint.go:589
#       0x1df9d09       github.com/grafana/loki/pkg/ingester.(*Checkpointer).Run+0x249                  /src/loki/pkg/ingester/checkpoint.go:613
#       0x1e1f9da       github.com/grafana/loki/pkg/ingester.(*walWrapper).run+0x23a                    /src/loki/pkg/ingester/wal.go:166

1 @ 0x43b225 0x44c397 0x1e0a695 0xc10682 0x472621
#       0x1e0a694       github.com/grafana/loki/pkg/ingester.(*Ingester).running+0xd4                   /src/loki/pkg/ingester/ingester.go:400
#       0xc10681        github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main+0x401    /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:190

1 @ 0x43b225 0x44c397 0x1e0af1e 0x472621
#       0x1e0af1d       github.com/grafana/loki/pkg/ingester.(*Ingester).loop+0x11d     /src/loki/pkg/ingester/ingester.go:448

1 @ 0x43b225 0x44c397 0x1f1e233 0xc10682 0x472621
#       0x1f1e232       github.com/cortexproject/cortex/pkg/cortex.NewServerService.func1+0xd2          /src/loki/vendor/github.com/cortexproject/cortex/pkg/cortex/server_service.go:28
#       0xc10681        github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main+0x401    /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:190

1 @ 0x43b225 0x44c397 0xb833c8 0x472621
#       0xb833c7        github.com/uber/jaeger-client-go/utils.(*reconnectingUDPConn).reconnectLoop+0xc7        /src/loki/vendor/github.com/uber/jaeger-client-go/utils/reconnecting_udp_conn.go:70

1 @ 0x43b225 0x44c397 0xb973fe 0x472621
#       0xb973fd        github.com/uber/jaeger-client-go.(*remoteReporter).processQueue+0xfd    /src/loki/vendor/github.com/uber/jaeger-client-go/reporter.go:296

1 @ 0x43b225 0x44c397 0xb9a725 0xb9a633 0x472621
#       0xb9a724        github.com/uber/jaeger-client-go.(*RemotelyControlledSampler).pollControllerWithTicker+0xa4     /src/loki/vendor/github.com/uber/jaeger-client-go/sampler_remote.go:153
#       0xb9a632        github.com/uber/jaeger-client-go.(*RemotelyControlledSampler).pollController+0x72               /src/loki/vendor/github.com/uber/jaeger-client-go/sampler_remote.go:148

1 @ 0x43b225 0x44c397 0xbc697b 0x1f2dd2b 0x472621
#       0xbc697a        github.com/weaveworks/common/signals.(*Handler).Loop+0x1ba      /src/loki/vendor/github.com/weaveworks/common/signals/signals.go:48
#       0x1f2dd2a       github.com/grafana/loki/pkg/loki.(*Loki).Run.func4+0x2a         /src/loki/pkg/loki/loki.go:298

1 @ 0x43b225 0x44c397 0xc121cb 0x1f2265d 0x1f3967c 0x43adf6 0x472621
#       0xc121ca        github.com/cortexproject/cortex/pkg/util/services.(*Manager).AwaitStopped+0x8a  /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/manager.go:145
#       0x1f2265c       github.com/grafana/loki/pkg/loki.(*Loki).Run+0x81c                              /src/loki/pkg/loki/loki.go:309
#       0x1f3967b       main.main+0x57b                                                                 /src/loki/cmd/loki/main.go:131
#       0x43adf5        runtime.main+0x255                                                              /usr/local/go/src/runtime/proc.go:225

1 @ 0x43b225 0x44c397 0xffe849 0xc10682 0x472621
#       0xffe848        github.com/cortexproject/cortex/pkg/ring/kv/memberlist.(*KVInitService).running+0xa8    /src/loki/vendor/github.com/cortexproject/cortex/pkg/ring/kv/memberlist/kv_init_service.go:74
#       0xc10681        github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main+0x401            /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:190

1 @ 0x43b225 0x44ce65 0x44ce4e 0x46e3e5 0x48d105 0x1c9eb97 0xc10682 0x472621
#       0x46e3e4        sync.runtime_Semacquire+0x44                                                            /usr/local/go/src/runtime/sema.go:56
#       0x48d104        sync.(*WaitGroup).Wait+0x64                                                             /usr/local/go/src/sync/waitgroup.go:130
#       0x1c9eb96       github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).loop+0x196    /src/loki/pkg/storage/stores/shipper/compactor/compactor.go:194
#       0xc10681        github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main+0x401            /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:190

1 @ 0x43b225 0x46e698 0x46e66e 0x489499 0xd378b2 0xd33ef6 0x101ca93 0x101d1de 0xbc56b1 0x1019865 0x10321b5 0xc10682 0x472621
#       0x46e66d        sync.runtime_notifyListWait+0xcd                                                /usr/local/go/src/runtime/sema.go:513
#       0x489498        sync.(*Cond).Wait+0x98                                                          /usr/local/go/src/sync/cond.go:56
#       0xd378b1        github.com/cortexproject/cortex/pkg/ring/kv/consul.(*mockKV).Get+0x411          /src/loki/vendor/github.com/cortexproject/cortex/pkg/ring/kv/consul/mock.go:141
#       0xd33ef5        github.com/cortexproject/cortex/pkg/ring/kv/consul.(*Client).WatchKey+0x2d5     /src/loki/vendor/github.com/cortexproject/cortex/pkg/ring/kv/consul/client.go:229
#       0x101ca92       github.com/cortexproject/cortex/pkg/ring/kv.(*prefixedKVClient).WatchKey+0xb2   /src/loki/vendor/github.com/cortexproject/cortex/pkg/ring/kv/prefix.go:45
#       0x101d1dd       github.com/cortexproject/cortex/pkg/ring/kv.metrics.WatchKey.func1+0x5d         /src/loki/vendor/github.com/cortexproject/cortex/pkg/ring/kv/metrics.go:99
#       0xbc56b0        github.com/weaveworks/common/instrument.CollectedRequest+0x270                  /src/loki/vendor/github.com/weaveworks/common/instrument/instrument.go:152
#       0x1019864       github.com/cortexproject/cortex/pkg/ring/kv.metrics.WatchKey+0x104              /src/loki/vendor/github.com/cortexproject/cortex/pkg/ring/kv/metrics.go:98
#       0x10321b4       github.com/cortexproject/cortex/pkg/ring.(*Ring).loop+0x94                      /src/loki/vendor/github.com/cortexproject/cortex/pkg/ring/ring.go:284
#       0xc10681        github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main+0x401    /src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:190

1 @ 0x46c41d 0x9d02ce 0x9d00a5 0x9ccc32 0x9de6a5 0x9dfef7 0x82da84 0x82f90d 0x9e19d3 0xbbf54c 0xbad22b 0xbbf885 0x82da84 0xbc00e9 0x82da84 0xb36064 0x82da84 0x831043 0x82c56d 0x472621
#       0x46c41c        runtime/pprof.runtime_goroutineProfileWithLabels+0x5c                           /usr/local/go/src/runtime/mprof.go:716
#       0x9d02cd        runtime/pprof.writeRuntimeProfile+0xcd                                          /usr/local/go/src/runtime/pprof/pprof.go:724
#       0x9d00a4        runtime/pprof.writeGoroutine+0xa4                                               /usr/local/go/src/runtime/pprof/pprof.go:684
#       0x9ccc31        runtime/pprof.(*Profile).WriteTo+0x3f1                                          /usr/local/go/src/runtime/pprof/pprof.go:331
#       0x9de6a4        net/http/pprof.handler.ServeHTTP+0x384                                          /usr/local/go/src/net/http/pprof/pprof.go:253
#       0x9dfef6        net/http/pprof.Index+0x8d6                                                      /usr/local/go/src/net/http/pprof/pprof.go:371
#       0x82da83        net/http.HandlerFunc.ServeHTTP+0x43                                             /usr/local/go/src/net/http/server.go:2069
#       0x82f90c        net/http.(*ServeMux).ServeHTTP+0x1ac                                            /usr/local/go/src/net/http/server.go:2448
#       0x9e19d2        github.com/gorilla/mux.(*Router).ServeHTTP+0xd2                                 /src/loki/vendor/github.com/gorilla/mux/mux.go:212
#       0xbbf54b        github.com/weaveworks/common/middleware.Instrument.Wrap.func1.2+0x4b            /src/loki/vendor/github.com/weaveworks/common/middleware/instrument.go:68
#       0xbad22a        github.com/felixge/httpsnoop.CaptureMetricsFn+0x24a                             /src/loki/vendor/github.com/felixge/httpsnoop/capture_metrics.go:81
#       0xbbf884        github.com/weaveworks/common/middleware.Instrument.Wrap.func1+0x324             /src/loki/vendor/github.com/weaveworks/common/middleware/instrument.go:67
#       0x82da83        net/http.HandlerFunc.ServeHTTP+0x43                                             /usr/local/go/src/net/http/server.go:2069
#       0xbc00e8        github.com/weaveworks/common/middleware.Log.Wrap.func1+0x1a8                    /src/loki/vendor/github.com/weaveworks/common/middleware/logging.go:52
#       0x82da83        net/http.HandlerFunc.ServeHTTP+0x43                                             /usr/local/go/src/net/http/server.go:2069
#       0xb36063        github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5+0x5e3     /src/loki/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:154
#       0x82da83        net/http.HandlerFunc.ServeHTTP+0x43                                             /usr/local/go/src/net/http/server.go:2069
#       0x831042        net/http.serverHandler.ServeHTTP+0xa2                                           /usr/local/go/src/net/http/server.go:2887
#       0x82c56c        net/http.(*conn).serve+0x8cc                                                    /usr/local/go/src/net/http/server.go:1952
```
</p>
</details>

**Comment by jyengk** [comment]
A similar issue happened in our setup too but with Loki version 2.2.0. The memory is never released but keeps on growing until Loki hits the resource limit, crashes and comes down again. 
Looks as though the querier does not release memory after any queries are executed. The pprof was of no help either since things looked all normal. 

setup: openshift + loki monolith + cassandra
The graph below is on my local setups. 

![image](https://user-images.githubusercontent.com/22469482/129034341-e2b6219e-b442-4296-9e26-9b78775ca29f.png)
![image](https://user-images.githubusercontent.com/22469482/129034436-8297fb45-2c45-41f4-af41-8d189ea71119.png)

On our scale environment, after queries are executed and the system stays idle, the memory is not released. Instead loki crashes:

![image](https://user-images.githubusercontent.com/22469482/129034996-2cfea632-d251-48e5-8a16-a22cc1c341fd.png)

**Comment by vikrantsde** [comment]
@jyengk  memory leak in queriers is fixed in Loki version 2.3.0

**Comment by jyengk** [comment]
We are still seeing the memory not being released with loki 2.3.0 + Openshift after performing queries while the rate of the entry of logs is consistent all throughout.
This is the container_memory_working_set_bytes for loki on openshift:
![image](https://user-images.githubusercontent.com/22469482/130079584-9cf767e3-350c-4783-8576-3b7178683037.png)

Oddly enough, the heap inuse bytes looks fine. 

![image](https://user-images.githubusercontent.com/22469482/130080735-45fa5ef4-7116-451a-ae8e-7f784cf4c695.png)

**Comment by jfolz** [comment]
@cyriltovena can I assume the issue of stuck open zstd decoders is on your radar?

**Comment by jfolz** [comment]
Regularly restarting Loki because of growing memory consumption is still very much relevant Mr. Stalebot.
