### ISSUE TITLE
Loki - Logged errors after following initial setup documentation.

### ISSUE THREAD

**Issue by MrDkVV** [grafana/loki#7928]
Hello, 

Sorry I'm new to Grafana and Loki so please feel free to direct me to get additional information. 

Background:

-  I've installed new "Docker" images of Grafana, Loki, and Promtail for the first time following documentation.
- In Grafana I'm monitoring logs and Errors are reported.
- Almost all configuration is default, so I would not expect the default install ( from using documentation ) to result in errors. Even if expected due to lack of configuration as documentation should advise how to correctly configure Loki correctly.

It is unclear why we are getting errors, I can collect and report logs, so what is this error even trying to say? as retry.go is the caller what is being retried as data looks successfully retrieved? 

Issue logs:

`

level=error ts=2022-12-13T17:55:41.383823304Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"
level=error ts=2022-12-13T17:55:41.383854854Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"
level=error ts=2022-12-13T17:55:41.383875564Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"
level=error ts=2022-12-13T17:55:41.383896383Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"
level=error ts=2022-12-13T17:55:41.383912614Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"
level=error ts=2022-12-13T17:55:41.383937652Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"
level=error ts=2022-12-13T17:55:41.383941569Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"
level=error ts=2022-12-13T17:55:41.383941159Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"
level=error ts=2022-12-13T17:55:41.383993809Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"
level=error ts=2022-12-13T17:55:41.383993849Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"
level=error ts=2022-12-13T17:55:41.38402582Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"
level=error ts=2022-12-13T17:55:41.384033865Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"
level=error ts=2022-12-13T17:55:41.384064543Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"
level=error ts=2022-12-13T17:55:41.384112926Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"
level=error ts=2022-12-13T17:55:41.391867191Z caller=scheduler_processor.go:182 org_id=fake msg="error notifying frontend about finished query" err="rpc error: code = Canceled desc = context canceled" frontend=172.17.0.3:9095
level=error ts=2022-12-13T17:55:41.39189289Z caller=scheduler_processor.go:137 org_id=fake msg="error notifying scheduler about finished query" err=EOF addr=172.17.0.3:9095

`

Current Configuration:

Grafana
`
# Directory where grafana can store logs
logs = /var/log/grafana
`

Loki
`
auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /var/lib/loki
  storage:
    filesystem:
      chunks_directory: /var/lib/loki/chunks
      rules_directory: /var/lib/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  retention_period: 90d
  retention_stream:
  - selector: '{container="loki-agent"}'
    priority: 1
    period: 24h
  reject_old_samples: true
  reject_old_samples_max_age: 7d 

querier:
  query_timeout: 15s
  max_concurrent: 500
  engine:
    timeout: 2m

compactor:
  retention_enabled: true
`

FirewallD on host:
`
[root@monster docker]# firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: enp68s0 wlp69s0
  sources: 
  services: dhcpv6-client ssh
  ports: 3000/tcp 9080/tcp 3100/tcp
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules
`

Host is Docker on CentOS 7.9

Loki Build:
`
docker volume create loki-volume
docker volume create loki-etc

wget https://raw.githubusercontent.com/grafana/loki/v2.7.0/cmd/loki/loki-local-config.yaml -O loki-config.yaml

docker container run -d -u loki -p 3100:3100 --name=loki-agent -v loki-volume:/var/lib/loki -v loki-etc:/etc/loki -v /var/log:/var/log --link grafana-agent docker.io/grafana/loki

` 

Granfana docker build:
`

#!/bin/bash

docker pull docker.io/grafana/grafana-enterprise

docker volume create grafana-volume
docker volume create grafana-etc

wget https://raw.githubusercontent.com/grafana/loki/v2.7.0/cmd/grafana/grafana-local-config.yaml -O grafana-config.yaml

docker container run -d -u grafana -p 3000:3000 --name=grafana-agent -v grafana-volume:/var/lib/grafana -v grafana-etc:/etc/grafana -v /var/log:/var/log docker.io/grafana/grafana-enterprise

`

Docker information:

`

docker ps 
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS              PORTS                    NAMES
d3456bc5aeb0        docker.io/grafana/promtail             "/usr/bin/promtail..."   6 days ago          Up 3 hours                                   promtail-agent
e51bd056caa6        docker.io/grafana/loki                 "/usr/bin/loki -co..."   6 days ago          Up About an hour    0.0.0.0:3100->3100/tcp   loki-agent
2f6dd043cf69        docker.io/grafana/grafana-enterprise   "/run.sh"                6 days ago          Up 3 hours          0.0.0.0:3000->3000/tcp   grafana-agent
[root@monster docker]# docker images
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
docker.io/grafana/grafana-enterprise   latest              c52059b19006        12 days ago         338 MB
docker.io/grafana/grafana              latest              179ad45e2c74        12 days ago         315 MB
docker.io/grafana/loki                 latest              970335e7116e        4 weeks ago         63 MB
docker.io/grafana/promtail             latest              dee0814b960d        4 weeks ago         191 MB
`

Please let me know if any additional information would be helpfull.

Thank you.
D

**Comment by MrDkVV** [comment]
Hi Woods, 

I already have a cloud setup working. 
Starting the offline testing phase and rand into the above.



Thank you.

**Comment by MrDkVV** [comment]
See 
https://community.grafana.com/t/loki-spams-deletion-related-error-messages/77462/2

I suspect this was fixed in Loki 2.7.1 after upgrading from 2.7.0

Thank you.

**Comment by shwedd** [comment]
Hi.
I updated loki and promtail to 2.7.1.
Errors remain
level=error ts=2022-12-14T08:23:12.088960104Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"

**Comment by jeschkies** [comment]
Are these error messages from Loki or Grafana? Could you try and query eg Loki's labels API directly?

**Comment by shwedd** [comment]
Errors message from Loki.
I try use logcli:
logcli-linux-amd64 query '{job="varlogs"}'
Error message:
loki[6581]: level=error ts=2022-12-16T06:42:56.763382327Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"

**Comment by JStickler** [comment]
Closing as stale. This issue was opened against a version of Loki that is no longer supported. If this issues still exists in more recent versions of Loki, please leave a comment and we can reopen the issue.
